let _browser = undefined;
let _sceneDiv = {}; // game output div
let _gameHost = undefined;
let _sceneData = undefined;
let _scenes = {};
let _gameOption = undefined;
let _serialLoadHistory = undefined;
let _browserComm = undefined;
let _gameData = undefined;
let _gameLevelTable = undefined;
let _resourcePool = undefined;